__title__ = 'spacymoji'
__version__ = '2.0.0'
__summary__ = 'spaCy pipeline component for adding emoji meta data to Doc, Token and Span objects.'
__uri__ = 'https://spacy.io'
__author__ = 'Ines Montani'
__email__ = 'ines@explosion.ai'
__license__ = 'MIT'
